import time 
lo = 10
while lo > 0:
    lo -= 1
    time.sleep(0.2)
    print "                                                          *   *    *"
    print "                                                          *   *    *"
    print "                                                          *   *    *"
    print "                                                          *****    *"
    print "                                                          *   *    *"
    print "                                                          *   *    *"
    print "                                                          *   *    *"
    time.sleep(0.2)
    print "                                                         *   *    * "
    print "                                                         *   *    * "
    print "                                                         *   *    * "
    print "                                                         *****    * "
    print "                                                         *   *    * "
    print "                                                         *   *    * "
    print "                                                         *   *    * "
    time.sleep(0.2)
    print "                                                        *   *    *  "
    print "                                                        *   *    *  "
    print "                                                        *   *    *  "
    print "                                                        *****    *  "
    print "                                                        *   *    *  "
    print "                                                        *   *    *  "
    print "                                                        *   *    *  "
    time.sleep(0.2)
    print "                                                       *   *    *   "
    print "                                                       *   *    *   "
    print "                                                       *   *    *   "
    print "                                                       *****    *   "
    print "                                                       *   *    *   "
    print "                                                       *   *    *   "
    print "                                                       *   *    *   "
    time.sleep(0.2)
    print "                                                      *   *    *    "
    print "                                                      *   *    *    "
    print "                                                      *   *    *    "
    print "                                                      *****    *    "
    print "                                                      *   *    *    "
    print "                                                      *   *    *    "
    print "                                                      *   *    *    "
    time.sleep(0.2)
    print "                                                     *   *    ******"
    print "                                                     *   *    *     "
    print "                                                     *   *    *     "
    print "                                                     *****    ******"
    print "                                                     *   *    *     "
    print "                                                     *   *    *     "
    print "                                                     *   *    ******"
    time.sleep(0.2)
    print "                                                    *   *    *******"
    print "                                                    *   *    *      "
    print "                                                    *   *    *      "
    print "                                                    *****    *******"
    print "                                                    *   *    *      "
    print "                                                    *   *    *      "
    print "                                                    *   *    *******"
    time.sleep(0.2)
    print "                                                   *   *    ********"
    print "                                                   *   *    *       "
    print "                                                   *   *    *       "
    print "                                                   *****    ********"
    print "                                                   *   *    *       "
    print "                                                   *   *    *       "
    print "                                                   *   *    ********"
    time.sleep(0.2)
    print "                                                  *   *    *********"
    print "                                                  *   *    *        "
    print "                                                  *   *    *        "
    print "                                                  *****    *********"
    print "                                                  *   *    *        "
    print "                                                  *   *    *        "
    print "                                                  *   *    *********"
    time.sleep(0.2)
    print "                                                 *   *    ********* "
    print "                                                 *   *    *         "
    print "                                                 *   *    *         "
    print "                                                 *****    *********        **"
    print "                                                 *   *    *                **"
    print "                                                 *   *    *                **"
    print "                                                 *   *    *********        **"
    time.sleep(0.2)
    print "                                                *   *    *********     *       *"
    print "                                                *   *    *              *     *"
    print "                                                *   *    *               *   *"
    print "                                                *****    *********        **"
    print "                                                *   *    *                **"
    print "                                                *   *    *                **"
    print "                                                *   *    *********        **"
    time.sleep(0.2)
    print "   *    *"
    print "   *    *"
    print "   *    *"
    print "   *    *"
    print "****    *"
    print "   *    *"
    print "   *    *"
    print "   *    *"
    time.sleep(0.2)
    print "  *    *"
    print "  *    *"
    print "  *    *"
    print "  *    *"
    print "***    *"
    print "  *    *"
    print "  *    *"
    print "  *    *"
    time.sleep(0.2)
    print " *   *"
    print " *   *"
    print " *   *"
    print " *   *"
    print "**   *"
    print " *   *"
    print " *   *"
    print " *   *"
    time.sleep(0.2)
    print "*   *"
    print "*   *"
    print "*   *"
    print "*   *"
    print "*   *"
    print "*   *"
    print "*   *"
    print "*   *"
    time.sleep(0.2)
    print "   *"
    print "   *"
    print "   *"
    print "   *"
    print "   *"
    print "   *"
    print "   *"
    print "   *"